import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { TRPCReactProvider } from "@/lib/trpc/client";
import { SiteNav } from "@/components/site-nav";
import { UserSwitcher } from "@/components/user-switcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TRPCReactProvider>
          <header className="flex items-center justify-between border-b px-4 py-2">
            <div className="flex items-center gap-6">
              <span className="font-semibold">Clip Campaigns</span>
              <SiteNav />
            </div>
            <UserSwitcher />
          </header>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
